### ISSUE TITLE
windows WLAN grabber not working

### ISSUE THREAD

**Issue by funniman12** [aleff-github/my-flipper-shits#11]
i put in my webhook and verified the webhook worked

**Comment by aleff-github** [comment]
> i put in my webhook and verified the webhook worked

If you are talking about `WLAN Windows Password`, what language do you have your computer in? This payload varies depending on the language of the computer as the entries reported are translated. I tested it in Italian and English but someone translated it into German (as you can see in Windows-Passwords-Multilang.ps1).

To do more specific checks and figure out what the problem is, try running the script as if you were simulating running the payload and let me know if running each step by hand can solve it or not.

In the past there was another person who wrote to me reporting the same or similar problem as you so I am interested in figuring out what the problem is.

**Comment by funniman12** [comment]
im pretty sure im in the uk version of english

**Comment by aleff-github** [comment]
> im pretty sure im in the uk version of english

Okay, and if you run the command `netsh wlan show profile` do you see the "All User Profile" entry?

Anyway, as I told you in the last message, try running the commands in the ps1 file by hand and tell me if you get errors back or not. Try the ENG version.
