### ISSUE TITLE
Spanish Configuration

### ISSUE THREAD

**Issue by dadowebfx** [aleff-github/my-flipper-shits#13]
Hi, i'm new with all this of the BadUsb. I tried to make many of the txt files to run from the flipper zero and i couldnt until i realize that i had to change the language of the keyboard. Would you please help me to find a solution to make them work on a spanish configuration? I already tried to change the keyboard configuration on the flipper zero to spanish but still no work, thanks.

**Comment by aleff-github** [comment]
> I already tried to change the keyboard configuration on the flipper zero to spanish but still no work, thanks.

I would have told you to check if you changed the keyboard correctly from the Flipper Zero settings, but evidently you have already done that.
Are you sure you have the Spanish keyboard on your computer?
For example, try creating a payload that simply uses the "STRING" function to write the alphabet in order, that way you can check if instead of writing "abcdefg..." you find some other thing like "wljsoeb..." this shows that it is a keyboard error and not some other thing.
In that case, if the keyboard on the computer is Spanish, on Flipper Zero is Spanish and still gives errors then it will be more complex to understand the problem and honestly I wouldn't know what to suggest except to try to format or update Flipper Zero.

**Comment by dadowebfx** [comment]
> > I already tried to change the keyboard configuration on the flipper zero to spanish but still no work, thanks.
> 
> I would have told you to check if you changed the keyboard correctly from the Flipper Zero settings, but evidently you have already done that. Are you sure you have the Spanish keyboard on your computer? For example, try creating a payload that simply uses the "STRING" function to write the alphabet in order, that way you can check if instead of writing "abcdefg..." you find some other thing like "wljsoeb..." this shows that it is a keyboard error and not some other thing. In that case, if the keyboard on the computer is Spanish, on Flipper Zero is Spanish and still gives errors then it will be more complex to understand the problem and honestly I wouldn't know what to suggest except to try to format or update Flipper Zero.

Hi again, thanks for the quick reply. 

The languaje settings on the computer and the keyboard is spanish. I downloaded english and changed the language settings and i was able to make the payload to work. Unfortunatly i do not think that is a solution but i might have found one and  it was actually easier than i thought. 

There is a Demo that comes with the flipper zero and the first time i used it i saw it said that it works even with non US keyboards. So there was the answer, instead of using STRING i used ALTSTRING, changed settings to spanish again and it worked just fine.

I hope that this might help anyone else with the same issue or similar.

Thank you.
